# Generated by Django 3.2.9 on 2022-01-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_img', models.ImageField(upload_to='project_image', verbose_name='Table of content Image')),
                ('introduction', models.CharField(max_length=100)),
                ('intro_desc', models.TextField(verbose_name='Introduction Description')),
                ('current', models.CharField(max_length=100, verbose_name='Current System')),
                ('current_desc', models.TextField(verbose_name='Current System Description')),
                ('proposed', models.CharField(max_length=100, verbose_name='Proposed New System')),
                ('prop_desc', models.TextField(verbose_name='Proposed Description')),
                ('problem', models.CharField(max_length=100, verbose_name='Problems Of Current System')),
                ('problem_desc', models.TextField(verbose_name='Problem of current system Description')),
                ('objectives', models.CharField(max_length=100, verbose_name='Objectives')),
                ('obj_description', models.TextField(verbose_name='Objectives Description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image')),
                ('file', models.FileField(upload_to='Projects/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Last price')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projectapp.category')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectdetail')),
            ],
            options={
                'ordering': ('-name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
