# Generated by Django 3.2.9 on 2022-01-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150, verbose_name='Course name')),
                ('topic', models.CharField(max_length=50, verbose_name='Project Topic')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('school_name', models.CharField(max_length=100, verbose_name='Name of your school')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
