# Generated by Django 3.2.9 on 2022-01-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='obj_description',
            new_name='obj_desc',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projectdetail'),
        ),
    ]
