# Generated by Django 3.2.9 on 2022-01-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20220118_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
