# Generated by Django 3.2.9 on 2022-01-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20220124_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Project Ratings'),
        ),
    ]
