# Generated by Django 3.2.9 on 2022-01-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_project_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Project Ratings'),
        ),
    ]
