# Generated by Django 3.2.9 on 2022-01-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
