# Generated by Django 3.2.9 on 2022-01-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_plan_userguid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase', verbose_name='Transaction invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='UserGuid',
        ),
    ]
