# Generated by Django 3.2.9 on 2022-01-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_delete_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
