# Generated by Django 3.2.9 on 2022-01-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20220108_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='course',
            field=models.CharField(max_length=150, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.TextField(verbose_name='Project Description'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Username')),
                ('email', models.EmailField(max_length=250, verbose_name='Your Email')),
                ('body', models.TextField(verbose_name='Your comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projectapp.project')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
