# Generated by Django 3.2.9 on 2022-01-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
