# Generated by Django 3.2.9 on 2022-01-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20220108_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='school_name',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='username',
            field=models.CharField(default=0, max_length=100, verbose_name='Your name'),
            preserve_default=False,
        ),
    ]
