# Generated by Django 3.2.9 on 2022-01-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20220109_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
