# Generated by Django 3.2.9 on 2022-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_wishlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.DateField(),
        ),
    ]
