# Generated by Django 3.2.9 on 2022-01-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_wishlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='username',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
