# Generated by Django 3.2.9 on 2022-01-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_alter_wishlist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='username',
            new_name='email',
        ),
    ]
