# Generated by Django 3.2.9 on 2022-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150, verbose_name='Course Name')),
                ('topic', models.CharField(max_length=50, verbose_name='Project Topic')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
