# Generated by Django 3.2.9 on 2022-01-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comment_plan_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='upload_image',
        ),
    ]
