# Generated by Django 3.2.9 on 2022-01-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_delete_purchase'),
        ('content', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload_image', models.FileField(upload_to='purchase')),
                ('paid', models.BooleanField(default=False)),
                ('project_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='projectapp.category')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
    ]
