# Generated by Django 3.2.9 on 2022-01-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_purchase_upload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='upload_image',
        ),
    ]
