# Generated by Django 3.2.9 on 2022-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.BigIntegerField(default=1, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
