# Generated by Django 3.2.9 on 2022-01-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_purchase_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
